# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo dev
  BINARY_NAME: govnocode

dotenv: [".env"]

tasks:
  build:
    cmds:
      - go build
        -tags prod
        -ldflags "-X main.GitCommit={{.COMMIT}}"
        -o dist/{{.BINARY_NAME}}
        ./cmd/{{.BINARY_NAME}}

  test:
    cmds:
      - go test ./... --race

  lint:
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4 run
