name: Go package

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: 1.26
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.4
          args: --timeout=5m

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: 1.26
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Run tests
        run: task test
